###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  mysql:
    image: 'mysql:8.0'
    container_name: adonisjs4-app-mysql
    working_dir: /application
    volumes:
      - '.:/app'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adonisjs_app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    restart: unless-stopped
    ports:
      - '20002:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: adonisjs4-app-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - '20003:80'

  adonis-api:
    #container_name: "${APP_NAME}-api"
    container_name: adonisjs4-app-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "20001:3333"
    depends_on:
      - mysql
    links:
      - mysql

  redis:
    #container_name: "${APP_NAME}-redis"
    container_name: adonisjs4-app-redis
    restart: always
    image: "redis:alpine"
    #ports:
    # - '6378:6379'
    volumes:
      - ./docker/data/redis:/data
    expose:
      - 6379